// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dsbasko/yandex-go-shortener/internal/service/urls (interfaces: Mutator)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mutator.go -package=mock_urls github.com/dsbasko/yandex-go-shortener/internal/service/urls Mutator
//

// Package mock_urls is a generated GoMock package.
package mock_urls

import (
	context "context"
	reflect "reflect"

	entity "github.com/dsbasko/yandex-go-shortener/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMutator is a mock of Mutator interface.
type MockMutator struct {
	ctrl     *gomock.Controller
	recorder *MockMutatorMockRecorder
}

// MockMutatorMockRecorder is the mock recorder for MockMutator.
type MockMutatorMockRecorder struct {
	mock *MockMutator
}

// NewMockMutator creates a new mock instance.
func NewMockMutator(ctrl *gomock.Controller) *MockMutator {
	mock := &MockMutator{ctrl: ctrl}
	mock.recorder = &MockMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutator) EXPECT() *MockMutatorMockRecorder {
	return m.recorder
}

// CreateURL mocks base method.
func (m *MockMutator) CreateURL(arg0 context.Context, arg1 entity.URL) (entity.URL, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURL", arg0, arg1)
	ret0, _ := ret[0].(entity.URL)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateURL indicates an expected call of CreateURL.
func (mr *MockMutatorMockRecorder) CreateURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURL", reflect.TypeOf((*MockMutator)(nil).CreateURL), arg0, arg1)
}

// CreateURLs mocks base method.
func (m *MockMutator) CreateURLs(arg0 context.Context, arg1 []entity.URL) ([]entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURLs", arg0, arg1)
	ret0, _ := ret[0].([]entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateURLs indicates an expected call of CreateURLs.
func (mr *MockMutatorMockRecorder) CreateURLs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURLs", reflect.TypeOf((*MockMutator)(nil).CreateURLs), arg0, arg1)
}

// DeleteURLs mocks base method.
func (m *MockMutator) DeleteURLs(arg0 context.Context, arg1 []entity.URL) ([]entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLs", arg0, arg1)
	ret0, _ := ret[0].([]entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteURLs indicates an expected call of DeleteURLs.
func (mr *MockMutatorMockRecorder) DeleteURLs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLs", reflect.TypeOf((*MockMutator)(nil).DeleteURLs), arg0, arg1)
}
