// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dsbasko/yandex-go-shortener/internal/service/urls (interfaces: URLProvider)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/url-provider.go -package=mock_urls github.com/dsbasko/yandex-go-shortener/internal/service/urls URLProvider
//

// Package mock_urls is a generated GoMock package.
package mock_urls

import (
	context "context"
	reflect "reflect"

	entities "github.com/dsbasko/yandex-go-shortener/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockURLProvider is a mock of URLProvider interface.
type MockURLProvider struct {
	ctrl     *gomock.Controller
	recorder *MockURLProviderMockRecorder
}

// MockURLProviderMockRecorder is the mock recorder for MockURLProvider.
type MockURLProviderMockRecorder struct {
	mock *MockURLProvider
}

// NewMockURLProvider creates a new mock instance.
func NewMockURLProvider(ctrl *gomock.Controller) *MockURLProvider {
	mock := &MockURLProvider{ctrl: ctrl}
	mock.recorder = &MockURLProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLProvider) EXPECT() *MockURLProviderMockRecorder {
	return m.recorder
}

// GetURLByOriginalURL mocks base method.
func (m *MockURLProvider) GetURLByOriginalURL(arg0 context.Context, arg1 string) (entities.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByOriginalURL", arg0, arg1)
	ret0, _ := ret[0].(entities.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByOriginalURL indicates an expected call of GetURLByOriginalURL.
func (mr *MockURLProviderMockRecorder) GetURLByOriginalURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByOriginalURL", reflect.TypeOf((*MockURLProvider)(nil).GetURLByOriginalURL), arg0, arg1)
}

// GetURLByShortURL mocks base method.
func (m *MockURLProvider) GetURLByShortURL(arg0 context.Context, arg1 string) (entities.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByShortURL", arg0, arg1)
	ret0, _ := ret[0].(entities.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByShortURL indicates an expected call of GetURLByShortURL.
func (mr *MockURLProviderMockRecorder) GetURLByShortURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByShortURL", reflect.TypeOf((*MockURLProvider)(nil).GetURLByShortURL), arg0, arg1)
}

// GetURLsByUserID mocks base method.
func (m *MockURLProvider) GetURLsByUserID(arg0 context.Context, arg1 string) ([]entities.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLsByUserID", arg0, arg1)
	ret0, _ := ret[0].([]entities.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLsByUserID indicates an expected call of GetURLsByUserID.
func (mr *MockURLProviderMockRecorder) GetURLsByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLsByUserID", reflect.TypeOf((*MockURLProvider)(nil).GetURLsByUserID), arg0, arg1)
}
